### ISSUE TITLE
Setting prompt to unicode character doesn't work as expected

### ISSUE THREAD

**Issue by jbarik** [cgdb/cgdb#257]
When I set my gdb prompt to : set prompt \033[1;33mgdbᗒ \033[0m
The prompt is set as expected but the cursor is 2/3 characters forward. Anything I type shows up 2/3 chars behind as shown below      

![cgd_unicode_prompt](https://user-images.githubusercontent.com/22386546/115032682-33492e00-9ee7-11eb-852b-1935cce1834a.gif)

If I launch plain gdb, I don't see this issue

**Comment by brasko** [comment]
The change from TERM=dumb to TERM=vanilla broke this. I'll have to undo that change.

It will fix this issue, but syntax coloring from GDB will not work in many cases.

**Comment by brasko** [comment]
I've pushed a change that should have resolved this issue, please let me know.
I had to reopen issue #251, which that change was meant to resolve.
At the moment, the GDB console will have no colored output i presume, which is something i'll need to fix before a release.

**Comment by jbarik** [comment]
The issue is still present

**Comment by auouymous** [comment]
This issue is present with or without the #251 patch. The patch could be re-applied to close that other issue.

It looks like gdb handles displaying of input and cgdb manages the cursor. But cgdb calculates cursor position using raw byte count, and multi-byte utf8 codepoints cause the cursor to be placed further to the right. A two byte codepoint `Γ` places it one additional character to the right, a three byte codepoint `☰` places it two additional characters to the right, and so on.

**Comment by auouymous** [comment]
This mostly fixes the issue. It is still broken for combining characters such as `◌̀`.

```patch
diff --git a/cgdb/scroller.cpp b/cgdb/scroller.cpp
index 41aefc5..be09c40 100644
--- a/cgdb/scroller.cpp
+++ b/cgdb/scroller.cpp
@@ -73,10 +73,10 @@ static char *parse(struct scroller *scr, struct hl_line_attr **attrs,
     static const int tab_size = cgdbrc_get_int(CGDBRC_TABSTOP);
     int tabcount = count(buf, buflen, '\t');
     int orig_len = strlen(orig);
-    int length = MAX(orig_len, scr->current.pos) + buflen +
+    int length = MAX(orig_len, scr->current.length) + buflen +
         (tab_size - 1) * tabcount + 1;
     char *rv = (char *) cgdb_calloc(length, 1);
-    int i, j;
+    int i, j, c;
     int debugwincolor = cgdbrc_get_int(CGDBRC_DEBUGWINCOLOR);
     int width, height;
 
@@ -86,7 +86,8 @@ static char *parse(struct scroller *scr, struct hl_line_attr **attrs,
     /* Copy over original buffer */
     strcpy(rv, orig);
 
-    i = scr->current.pos;
+    c = scr->current.pos;
+    i = scr->current.length;
 
     /* Expand special characters */
     for (j = 0; j < buflen; j++) {
@@ -99,16 +100,19 @@ static char *parse(struct scroller *scr, struct hl_line_attr **attrs,
             case 127:
                 if (i > 0)
                     i--;
+                if (c > 0)
+                    c--;
                 break;
                 /* Tab -> Translating to spaces */
             case '\t':
                 do {
                     rv[i++] = ' ';
-                } while (i % tab_size != 0);
+                    c++;
+                } while (c % tab_size != 0);
                 break;
                 /* Carriage return -> Move back to the beginning of the line */
             case '\r':
-                i = 0;
+                i = c = 0;
                 if ((buflen - j) >= 1 && buf[j + 1] != '\n') {
                     sbfree(*attrs);
                     *attrs = NULL;
@@ -139,11 +143,13 @@ static char *parse(struct scroller *scr, struct hl_line_attr **attrs,
                 break;
             default:
                 rv[i++] = buf[j];
+                c += (buf[j] & 0xC0) != 0x80;
                 break;
         }
     }
 
-    scr->current.pos = i;
+    scr->current.pos = c;
+    scr->current.length = i;
 
     /**
      * The prompt should never be longer than the width of the terminal.
@@ -197,6 +203,7 @@ struct scroller *scr_new(SWINDOW *win)
     rv->current.r = 0;
     rv->current.c = 0;
     rv->current.pos = 0;
+    rv->current.length = 0;
     rv->in_scroll_mode = 0;
     rv->lines_to_display = 0;
     rv->win = win;
@@ -339,6 +346,7 @@ static void scr_add_buf(struct scroller *scr, const char *buf)
 
         /* Expand the buffer */
         scr->current.pos = 0;
+        scr->current.length = 0;
 
         /* Add the new line */
         line = parse(scr, &attrs, "", buf, distance);
diff --git a/cgdb/scroller.h b/cgdb/scroller.h
index eb88bbd..b7089ce 100644
--- a/cgdb/scroller.h
+++ b/cgdb/scroller.h
@@ -55,7 +55,8 @@ struct scroller {
     struct {
         int r;                  /* Current line (row) number */
         int c;                  /* Current column number */
-        int pos;                /* Cursor position in last line */
+        int pos;                /* Cursor position in last line in characters */
+        int length;             /* Length of last line in bytes */
     } current;
 
     /** If in search mode. 1 if searching, 0 otherwise */
```

**Comment by brasko** [comment]
Thanks for the patch, I'll investigate this soon.

**Comment by auouymous** [comment]
Another problem is double-cell characters `め` and zero-width characters "\u200B".

**Comment by brasko** [comment]
I've been quite busy. I'd just like to say I'll try to review this soonish.

I'm looking at introducing libvterm into cgdb and that would have a big impact on areas of the code, like this, I believe.

**Comment by brasko** [comment]
I've finally made some progress on integrating cgdb with libvterm.
@jbarik , @auouymous Could you please build cgdb from the libvterm branch and let me know if it resolves all the issues found above?

**Comment by auouymous** [comment]
Yes and no. It displays the correct number of spaces for the zero-width, wide and combining characters when the locale does not support them. And it properly works with combining and zero-width characters with a correct locale, but wide characters cause a tilde to be inserted after the character, and the cursor position does not account for it. Every wide character has its own tilde, and after a couple, the cursor is inside the prompt.

You can test by adding `set prompt めgdbめ > ` in `.gdbinit`.

**Comment by brasko** [comment]
@auouymous Thanks for all the valuable feedback!

I just pushed a fix for wide unicode support. Please give this a shot and let me know if it works! Thanks!

**Comment by auouymous** [comment]
Wide characters work fine now in the prompt and when typed.

**Comment by brasko** [comment]
I've integrated the libvterm branch into master. This should have fixed this issue. Please let me know otherwise. Thanks!

**Comment by limitedAtonement** [comment]
When can we expect a tag with this fix in it? Once that tag is in place, I can mark https://archlinux.org/packages/community/x86_64/cgdb/ as out of date (they'll probably update it before I even get a chance to do that!), then I can have this new awesome version!

**Comment by brasko** [comment]
I think it'll be at least a week, maybe a bit more.

I've got a few open bugs to fix, I've got to update to the latest vterm, and I want to bring in Michael Sartain's pull request.

**Comment by limitedAtonement** [comment]
Sweet! A couple weeks is no sweat at all! Thank you for making cgdb great!!
